$Step-1$

## import required packages ##

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# ERROR
# WARNING
# if you want to avoid warnings import warnings


In [4]:
df=pd.read_csv(r'C:\Users\aramaiah.ASUAD\Documents\My Data Science notes\Data_files_data_science\winequality_red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
# make sure that 
# after reading thet data
# eda
# befeore we aply ml model data should be in  numerical format
# we already dd eda for 10 days
# assume that eda is completed
# assume the data is numerical data




# Divide the data ito two parts train and teat 
# Train data X_Train and y_Train
# 

In [ ]:
We need to perform EDA
but we have completd Numerical data
- we didvide the data into two parts input data and output data
- input data = X ; output data= y
- again we divide input data into two parts i.e train and test
- input train data = x_train ; input test data is y_test
- similarly we divide the output data into two parts i.e train and test
- output train data =y_train ; output test data =y_test
- model development happens on train data i.e X_train and y_train
-  X_test will pass through the developed model data these are called y_predictions
- Y-predictions compare with y-test



In [ ]:
data frame name:df
Target coulmn: quality
remaining columnsL

$Step-3$
## Divide the data into two part input and output

In [5]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
# I want input coulmns data 
#  Drop the target column 
# I want output columns data 
#  Select the output column


In [10]:
X=df.drop('quality',axis=1)
y=df['quality']

In [14]:
X #this is the df having only input columns 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [11]:
y #this is the output column

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
X====== X_train and X_test
y ====== y_train and y_test

sklearn.model selection  ========> train test split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
train_test_split(X,y,test_size=0.2)

[      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 700            10.6             1.020         0.43             2.9      0.076   
 349             9.1             0.785         0.00             2.6      0.093   
 1462            6.8             0.640         0.03             2.3      0.075   
 1198            7.7             0.260         0.26             2.0      0.052   
 201             8.8             0.370         0.48             2.1      0.097   
 ...             ...               ...          ...             ...        ...   
 945            10.2             0.440         0.42             2.0      0.071   
 813             6.9             0.390         0.24             2.1      0.102   
 695             5.1             0.470         0.02             1.3      0.034   
 1346            6.1             0.590         0.01             2.1      0.056   
 703             7.5             0.380         0.48             2.6      0.073   
 
       free su

$Step-4$
# Divide the data into train and test
 - will use train and test split from sklearn model selection 
 - It will take the following parameters
    - X:input data
    - y:output data
    - test-size = 0.3,30% test data 70% train data 
    - by default 75:25
    - random state
        - we want select observations randomly 
        - many possible combinations
        - every possible combination represent as a number

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,random_state=1234,test_size=0.30)

In [ ]:
# shape of X_train:
# shape of X_test:
# shape of y_train:
# shape of y_test:

$Check-point number 1 $

In [20]:
# check the shape
# df.shape
df.shape

(1599, 12)

In [21]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
642             9.9             0.540         0.45             2.3      0.071   
678             8.3             0.780         0.10             2.6      0.081   
412             7.1             0.735         0.16             1.9      0.100   
73              8.3             0.675         0.26             2.1      0.084   
985             7.4             0.580         0.00             2.0      0.064   
...             ...               ...          ...             ...        ...   
1228            5.1             0.420         0.00             1.8      0.044   
1077            8.6             0.370         0.65             6.4      0.080   
1318            7.5             0.630         0.27             2.0      0.083   
723             7.1             0.310         0.30             2.2      0.053   
815            10.8             0.450         0.33             2.5      0.099   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
642                  16.0                  40.0  0.99910  3.39       0.62   
678                  45.0                  87.0  0.99830  3.48       0.53   
412                  15.0                  77.0  0.99660  3.27       0.64   
73                   11.0                  43.0  0.99760  3.31       0.53   
985                   7.0                  11.0  0.99562  3.45       0.58   
...                   ...                   ...      ...   ...        ...   
1228                 18.0                  88.0  0.99157  3.68       0.73   
1077                  3.0                   8.0  0.99817  3.27       0.58   
1318                 17.0                  91.0  0.99616  3.26       0.58   
723                  36.0                 127.0  0.99650  2.94       1.62   
815                  20.0                  38.0  0.99818  3.24       0.71   

      alcohol  
642       9.4  
678      10.0  
412       9.3  
73        9.2  
985      11.3  
...       ...  
1228     13.6  
1077     11.0  
1318      9.8  
723       9.5  
815      10.8  

[1119 rows x 11 columns]

In [22]:
X_train.shape

(1119, 11)

In [23]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  
688       9.4  
961       9.3  
726      11.1  
537      10.7  
1544     11.2  
...       ...  
1461     10.0  
1591     11.6  
1045     11.4  
1498     10.8  
42       10.5  

[480 rows x 11 columns]

In [25]:
X_test.shape

(480, 11)

In [26]:
y_test

688     5
961     5
726     6
537     6
1544    7
       ..
1461    4
1591    6
1045    6
1498    6
42      6
Name: quality, Length: 480, dtype: int64

In [27]:
y_test.shape

(480,)

In [28]:
y_train

642     5
678     5
412     5
73      4
985     6
       ..
1228    7
1077    5
1318    6
723     5
815     5
Name: quality, Length: 1119, dtype: int64

In [29]:
y_train.shape

(1119,)

In [30]:
df.dropna(inplace=True) #drop the null  value 
df.reset_index(drop=True,inplace=True)
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [31]:
df.shape

(1599, 12)

In [32]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [33]:
# Step_1: Read the packages 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')



In [34]:
# Step-2: Read the file 
df=pd.read_csv(r'C:\Users\aramaiah.ASUAD\Documents\My Data Science notes\Data_files_data_science\winequality_red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [35]:
#  Step3: Do the EDA : end to end eda shouls be performed i.e cateagorical sould be converted to numerical
# and nderstand the important features i.e feature selection

In [37]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [36]:
# Step-4: Divide into X and y i.e input and out variables
X=df.drop('quality',axis=1)
y=df['quality']

In [ ]:
# Step-5: train test split
from sklearn.model_selection  

In [38]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

In [41]:
y_predictions=LR.predict(X_test)
y_predictions

array([5.15272674, 5.32546327, 5.63662519, 5.51245819, 6.35588496,
       5.39028618, 5.37580837, 5.94379165, 5.49446987, 6.98211458,
       4.92847919, 5.18177228, 5.73271386, 5.56085417, 5.53985028,
       5.25272042, 4.93424659, 5.12423646, 6.27626835, 5.12589226,
       5.06691612, 5.91039778, 5.1797551 , 5.45854364, 5.72531378,
       6.31002431, 5.30913419, 5.50678991, 6.04808131, 5.47609822,
       4.72291628, 6.20818055, 5.21920961, 5.62421184, 5.55062526,
       5.52259916, 6.36735043, 5.23288886, 5.49938736, 5.80792898,
       5.16587916, 6.13318292, 5.72636822, 5.33537114, 5.63701918,
       4.96463531, 4.88029661, 5.78938553, 6.36333952, 5.56149953,
       4.95005899, 5.75085354, 6.67236186, 6.16951277, 5.34056761,
       5.12096361, 6.19641543, 5.21584694, 6.46449078, 5.25590493,
       5.27667097, 5.17871421, 5.09122333, 5.63083824, 5.01946398,
       6.16336001, 5.7427919 , 6.337122  , 5.28732968, 6.05063646,
       5.7342916 , 5.57340483, 5.21043842, 6.18633591, 5.50678

In [44]:
X_test.values[0]

array([7.7   , 0.66  , 0.04  , 1.6   , 0.039 , 4.    , 9.    , 0.9962,
       3.4   , 0.47  , 9.4   ])

In [45]:
y_test

688     5
961     5
726     6
537     6
1544    7
       ..
1461    4
1591    6
1045    6
1498    6
42      6
Name: quality, Length: 480, dtype: int64

In [46]:
df1=pd.DataFrame()
df1=X_test
df1['y']=y
df1['y_pred']=y_predictions
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
688             7.7             0.660         0.04             1.6      0.039   
961             7.1             0.560         0.14             1.6      0.078   
726             8.1             0.720         0.09             2.8      0.084   
537             8.1             0.825         0.24             2.1      0.084   
1544            8.4             0.370         0.43             2.3      0.063   
...             ...               ...          ...             ...        ...   
1461            6.2             0.785         0.00             2.1      0.060   
1591            5.4             0.740         0.09             1.7      0.089   
1045            6.9             0.440         0.00             1.4      0.070   
1498            6.6             0.895         0.04             2.3      0.068   
42              7.5             0.490         0.20             2.6      0.332   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
688                   4.0                   9.0  0.99620  3.40       0.47   
961                   7.0                  18.0  0.99592  3.27       0.62   
726                  18.0                  49.0  0.99940  3.43       0.72   
537                   5.0                  13.0  0.99720  3.37       0.77   
1544                 12.0                  19.0  0.99550  3.17       0.81   
...                   ...                   ...      ...   ...        ...   
1461                  6.0                  13.0  0.99664  3.59       0.61   
1591                 16.0                  26.0  0.99402  3.67       0.56   
1045                 32.0                  38.0  0.99438  3.32       0.58   
1498                  7.0                  13.0  0.99582  3.53       0.58   
42                    8.0                  14.0  0.99680  3.21       0.90   

      alcohol  y    y_pred  
688       9.4  5  5.152727  
961       9.3  5  5.325463  
726      11.1  6  5.636625  
537      10.7  6  5.512458  
1544     11.2  7  6.355885  
...       ... ..       ...  
1461     10.0  4  5.163071  
1591     11.6  6  5.556391  
1045     11.4  6  6.167418  
1498     10.8  6  5.271424  
42       10.5  6  5.674091  

[480 rows x 13 columns]

In [ ]:
# metrix

In [ ]:
# # batch means 
# at a time 100 test samples
# at a time 10 test samples
# for example X_test : 480
    
    
    
# real time means 
# instaed of apping muliple observations we can pass singel test case

In [47]:
# model name: LR
# Model trained with hoe many columns: 11 columns 
#  in order to get the output 
#  new teat case also should have how many 

In [50]:
LR.predict([[1,2,3,4,6,7,5,8,9,8,12]])

array([-85.64468825])

In [51]:
LR.predict([[1,2,3,45,6,75,87,98,12,34,65]])

array([-1134.19701066])

In [52]:
ip1=[1,2,3,45,6,75,87,98,12,34,65]
LR.predict([ip1])

array([-1134.19701066])

# Model evaluation

In [55]:
# RMSE
# MSE
# MAE
# R-square
from sklearn.metrics import r2_score,mean_squared_error

In [54]:
r2_score(y_test,y_predictions)

0.31285862790752283

In [57]:
MSE=mean_squared_error(y_test,y_predictions)
MSE

0.3918584723116435